//
// Created by mile on 9/11/19.
//

#ifndef TALLER_MICROMACHINES_PROTECTEDQUEUESTATE_H
#define TALLER_MICROMACHINES_PROTECTEDQUEUESTATE_H


class ProtectedQueueState {

};


#endif //TALLER_MICROMACHINES_PROTECTEDQUEUESTATE_H
