
#ifndef TALLER_MICROMACHINES_COMMUNICATIONCONSTANTS_H
#define TALLER_MICROMACHINES_COMMUNICATIONCONSTANTS_H

#define J_PLAYERS "players"
#define J_MAXPLAYERS "max_players"
#define J_CARS "cars"
#define J_WAITFORPLAYERS "waitforplayers"
#define J_CENTER "center"
#define J_USER "user"
#define J_ELEMENTS "elements"
#define J_ID "id"
#define J_SPEED "speed"
#define J_X "x"
#define J_Y "y"
#define J_ANGLE "angle"
#define J_MUD "mud"
#define J_MUDS "muds"
#define J_LIVES "lives"
#define J_CRASH "crash"
#define J_OILS "oils"
#define J_BOULDERS "boulders"
#define J_POS "pos"
#define J_END "end"
#define J_LAPS "lap"
#define J_TOTALLAPS "total_laps"
#define J_CONSUMED "consumed"
#define J_TRACKS "tracks"
#define J_CURVED "curved"
#define J_CURVED_CENTER "curved_center"
#define J_HEALTH "health"
#define J_BOOST "boost"
#define J_NAME "name"
#define J_STRAIGHT "straight"
#define J_X0 "x0"
#define J_Y0 "y0"
#define J_X1 "x1"
#define J_Y1 "y1"
#define J_X2 "x2"
#define J_Y2 "y2"


#endif //TALLER_MICROMACHINES_COMMUNICATIONCONSTANTS_H
