#ifndef TALLER_MICROMACHINES_CONSTANTS_H
#define TALLER_MICROMACHINES_CONSTANTS_H


#define TRACK 0
#define CAR 1
#define MUD 2
#define OIL 3
#define STONE 4
#define BOOST 5
#define HEALTH 6
#define LIMIT 7


#define W 6.9
#define H 5.5

#define FIRST_GROUND_TILE_X -31.05
#define FIRST_GROUND_TILE_Y 0.0
#define FIRST_GROUND_TILE_ANGLE 0.0

#define FIRST_CEILING_TILE_X -31.05
#define FIRST_CEILING_TILE_Y 74.5
#define FIRST_CEILING_TILE_ANGLE 0.0

#define FIRST_LEFT_TILE_X -37.25
#define FIRST_LEFT_TILE_Y 6.2
#define FIRST_LEFT_TILE_ANGLE 90.0

#define FIRST_RIGHT_TILE_X 37.25
#define FIRST_RIGHT_TILE_Y 6.2
#define FIRST_RIGHT_TILE_ANGLE 90.0

#define STARTPOINT_X 265
#define STARTPOINT_Y 0

#define CAR_RESIZE_FACTOR 4


#endif //TALLER_MICROMACHINES_CONSTANTS_H
