#ifndef TALLER_MICROMACHINES_MOVETYPE_H
#define TALLER_MICROMACHINES_MOVETYPE_H

enum MoveType {
    UP, DOWN, LEFT, RIGHT, UPLEFT, UPRIGHT, DOWNLEFT, DOWNRIGHT
};


#endif //TALLER_MICROMACHINES_MOVETYPE_H
