//
// Created by casimiro on 29/10/19.
//

#ifndef TALLER_MICROMACHINES_MOVETYPE_H
#define TALLER_MICROMACHINES_MOVETYPE_H

#endif //TALLER_MICROMACHINES_MOVETYPE_H


class enum MoveType {UP, DOWN, LEFT, RIGHT};